name: Shipping sample CI actions
on: [push]
jobs:
  Run-CI-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build monolith
        run: |
          cd monolith
          mvn -B -ntp clean verify
